### ISSUE TITLE
Composer package

### ISSUE THREAD

**Issue by luizpedone** [etsy/feature#3]
Hi, first of all, thanks for making this API public! =)

I've noticed that it's not a composer package yet. Since PHP community moved towards Composer, it would be really nice to have etsy/feature as a composer package. There's any way we could have it there? If any help is needed, let me know.

Thanks!

**Comment by pdt256** [comment]
+1

**Comment by x0e-foobar** [comment]
+1

**Comment by matt2000** [comment]
:+1:

**Comment by martindilling** [comment]
Any news on submitting this on https://packagist.org/? :)

**Comment by matt2000** [comment]
I'd accept a PR adding composer support at https://github.com/matt2000/feature, or else I'll add it myself eventually.

**Comment by Atriedes** [comment]
already done : https://packagist.org/packages/jowy/feature
